### ISSUE TITLE
leanprover-community-bot takes up a spot in the "# by commits" column

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/mathlib_stats#5]
<img width="1176" alt="Screen Shot 2020-08-11 at 12 14 11 AM" src="https://user-images.githubusercontent.com/5209952/89856581-a388fe00-db67-11ea-9202-cd76eefebf77.png">

Since https://github.com/leanprover-community/mathlib_stats/commit/e6d61c0918ca9fc85b083891f4b6e8576c6ab635, the "# by commits" column skips a number (the ranking of leanprover-community-bot).

(This is low priority, but since Kevin noticed, we may as well have an open issue in case it bugs anyone else: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mathlib.20stats/near/205071897)

**Comment by benjamindavidson** [comment]
Similar "issue": mergify-bot also takes up a place on the list (although unlike leanprover-community-bot, mergify-bot's row is visible in the table).
<img width="931" alt="Screen Shot 2021-04-13 at 2 20 37 AM" src="https://user-images.githubusercontent.com/68528197/114505802-ec191f80-9bfe-11eb-9ba7-fcebbcfa2d4f.png">
