### ISSUE TITLE
duplicate entries in the "Authors" table

### ISSUE THREAD

**Issue by benjamindavidson** [leanprover-community/mathlib_stats#9]
I noticed that for a number of users, their first contribution is seemingly not recognized as being made by the same account as their subsequent contributions, causing that initial contribution to be listed solitarily as a separate author. I'll use myself as an example in the following screengrabs, but I've seen this for a handful of other users as well.

<img width="929" alt="Screen Shot 2021-04-12 at 10 24 16 AM" src="https://user-images.githubusercontent.com/68528197/114410703-9484a080-9b79-11eb-9194-d16a7f1698c2.png">
<img width="926" alt="Screen Shot 2021-04-12 at 10 24 52 AM" src="https://user-images.githubusercontent.com/68528197/114410717-964e6400-9b79-11eb-8a9b-39bea025c5f8.png">

Obviously this _very_ low-priority, but I thought I'd open an issue all the same.

**Comment by bryangingechen** [comment]
Ah, entries are de-duplicated in a [`.mailmap`](https://shane.io/2011/10/07/git-shortlog-and-mailmap.html) file which I've been maintaining. It's stored in a private repository to prevent spambots from trivially grabbing all of our emails (though those emails are also available from the mathlib repo git history).

It looks like there was a duplicate entry in there which was causing this. I've just pushed an update; let me know if it doesn't fix it in a day or so.

**Comment by benjamindavidson** [comment]
@bryangingechen Thanks! I'll keep an eye on it.

**Comment by benjamindavidson** [comment]
Looks like this is fixed! Thank you, Bryan!
